// Generated by CoffeeScript 1.4.0
var get, set;

get = Em.get;

set = Em.set;

module.exports = function(url) {
  if (url == null) {
    url = '/users/me';
  }
  return Em.Application.initializer({
    name: "user",
    initialize: function(container, App) {
      var UserController;
      UserController = Em.ObjectController.extend({
        init: function() {
          var that;
          that = this;
          return Em.$.ajax({
            url: url,
            type: 'GET',
            contentType: 'application/json',
            success: function(key) {
              var user;
              if (key !== '') {
                user = App.User.find(key);
                return set(that, 'content', user);
              }
            }
          });
        }
      });
      container.register('user', 'main', UserController);
      container.lookup('user:main');
      container.typeInjection('controller', 'user', 'user:main');
      return container.typeInjection('route', 'user', 'user:main');
    }
  });
};
