// Generated by CoffeeScript 1.6.1

describe('UserController', function() {
  return it('should be injected to routes and controllers', function(done) {
    var App;
    Em.$.ajax = function() {};
    require('ember-user')();
    App = Em.Application.create({
      ready: function() {
        var controller, route;
        controller = App.__container__.lookup('user:main');
        assert(controller);
        controller = App.__container__.lookup('controller:some');
        assert(controller.hasOwnProperty('user'));
        route = App.__container__.lookup('route:some');
        return assert(route.hasOwnProperty('user'));
      }
    });
    App.SomeController = Em.Controller.extend();
    App.SomeRoute = Em.Route.extend();
    App.destroy();
    return done();
  });
});
