// Generated by CoffeeScript 1.6.2
module.exports = function(url) {
  if (url == null) {
    url = '/users/me/';
  }
  Em.Application.initializer({
    name: "user",
    initialize: function(container, App) {
      var ObjectController;

      ObjectController = Em.ObjectController.extend({
        init: function() {
          var that;

          that = this;
          return Em.$.ajax({
            url: url,
            type: 'GET',
            contentType: 'application/json',
            success: function(res) {
              if (res !== '') {
                if (typeof res === 'string') {
                  res = App.User.find(res);
                }
                return that.set('content', res);
              }
            }
          });
        }
      });
      container.register('user:main', ObjectController);
      return container.lookup('user:main');
    }
  });
  return Em.Application.initializer({
    name: 'injectUser',
    initialize: function(container, App) {
      container.typeInjection('controller', 'user', 'user:main');
      return container.typeInjection('route', 'user', 'user:main');
    }
  });
};
